### ISSUE TITLE
Implement startNewPasswordRequired()

### ISSUE THREAD

**Issue by ghost** [BruceBuckland/SignIn-awsmhh#2] opened 2016-10-27 14:56 UTC
Implement method `startNewPasswordRequired()` to allow user to set a new password.

If my understanding of Cognito is correct, new user created by Cognito console cannot be used because of FORCE_CHANGE_PASSWORD status: he/she cannot even authentify.

**Comment by BruceBuckland** [comment] 2016-10-27 15:47
@Domsware 

thank you for your comment.
Sign-up is possible from within the app 

If you use "Signup Now!" on the Sign-In page, it will allow you to create a user, and set a password, and it will send you a confirmation code and create a confirmed user if you enter the code.

I do see the problem you reported.  I just tried to add a user through the AWS Console (as opposed to throught the app, I had never tried to create a user in the console before - I didn't even know it was possible) and I see that I need to implement a delegate protocol for startCustomAuthentication.  I cannot however find the startNewPasswordRequired delegate method you mention.

However for the most popular use cases, the following seems to be a reasonable *changeable priority list. I would include your contribution (after review) if you want to implement any of these.

1) We need to make the Google and Facebook providers use WKWebView instead of Safari. Because the use of Safari in this way (apparently) can result in being rejected for the app store.

2) We need to make it possible to confirm a password change or an attribute update after leaving the app or leaving the confirmation screen.  Currently if the app gets restarted or the user backs out of the confirmation screen, the update is never completed.  The user can "re-make" the attribute change or password update, but he can't get back to a place where he can re-enter the confirmation code.

3) The old signin did the delegate based AWSCognitoIdentityInteractiveAuthenticationDelegate approach  (although it did not do startNewPasswordRequired() either.).  I hope to re-implement that process in SignIn-awsmhh. 

4) AWSSignInProviders are needed for Twitter, Salesforce, Yahoo, PayPal and Microsoft.

5) Implement startCustomAuthentication()

**Comment by ghost** [comment] 2016-10-28 09:42
As for me as I am new to AWS I only use AWS Console for now! Maybe I can change this status using CLI... Have to check it.

`startNewPasswordRequired()` is an optional method of 
`AWSCognitoIdentityInteractiveAuthenticationDelegate` protocol.

**Comment by BruceBuckland** [comment] 2016-11-17 16:23
The latest version of Mobile Hub has code to handle the interactive delegate. So the answer to this is to design extensions to the downloaded code from Mobile Hub not to change this repository, so I am closing this issue.

**Closed as completed by BruceBuckland** 2016-11-17 16:23 UTC
Labels: enhancement
